--
-- PostgreSQL database dump
--


-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0
CREATE DATABASE kataev;

\c kataev;


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: app; Type: SCHEMA; Schema: -; Owner: app
--
CREATE SCHEMA app;


ALTER SCHEMA app OWNER TO app;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: KataevPartners; Type: TABLE; Schema: app; Owner: app
--

CREATE TABLE app."KataevPartners" (
    "KataevId" integer NOT NULL,
    "KataevName" text,
    "KataevPartnerType" text,
    "KataevRating" integer NOT NULL,
    "KataevAddress" text,
    "KataevINN" text,
    "KataevDirectorLastName" text,
    "KataevDirectorFirstName" text,
    "KataevDirectorMiddleName" text,
    "KataevPhone" text,
    "KataevEmail" text
);


ALTER TABLE app."KataevPartners" OWNER TO app;

--
-- Name: KataevPartners_KataevId_seq; Type: SEQUENCE; Schema: app; Owner: app
--

ALTER TABLE app."KataevPartners" ALTER COLUMN "KataevId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app."KataevPartners_KataevId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: KataevProducts; Type: TABLE; Schema: app; Owner: app
--

CREATE TABLE app."KataevProducts" (
    "KataevId" integer NOT NULL,
    "KataevName" text,
    "KataevArticle" text,
    "KataevType" text
);


ALTER TABLE app."KataevProducts" OWNER TO app;

--
-- Name: KataevProducts_KataevId_seq; Type: SEQUENCE; Schema: app; Owner: app
--

ALTER TABLE app."KataevProducts" ALTER COLUMN "KataevId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app."KataevProducts_KataevId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: KataevSalesHistory; Type: TABLE; Schema: app; Owner: app
--

CREATE TABLE app."KataevSalesHistory" (
    "KataevId" integer NOT NULL,
    "KataevPartnerId" integer NOT NULL,
    "KataevProductId" integer NOT NULL,
    "KataevQuantity" integer NOT NULL,
    "KataevSaleDate" timestamp without time zone NOT NULL
);


ALTER TABLE app."KataevSalesHistory" OWNER TO app;

--
-- Name: KataevSalesHistory_KataevId_seq; Type: SEQUENCE; Schema: app; Owner: app
--

ALTER TABLE app."KataevSalesHistory" ALTER COLUMN "KataevId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app."KataevSalesHistory_KataevId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: KataevPartners; Type: TABLE DATA; Schema: app; Owner: app
--

COPY app."KataevPartners" ("KataevId", "KataevName", "KataevPartnerType", "KataevRating", "KataevAddress", "KataevINN", "KataevDirectorLastName", "KataevDirectorFirstName", "KataevDirectorMiddleName", "KataevPhone", "KataevEmail") FROM stdin;
1	ООО "ПРИКОЛ"	Интернет-магазин	7	Петропавловская ул., 73А, Пермь, Пермский край, 614045	55373818	Дуданов	Олег	Васильевич	799999999	dudanov.O@mail.ru
2	ИП Смирнов В.А.	Оптовый покупатель	10	ул. Попова, 58Б, Пермь, Пермский край, 614000	38098754	Смирнов	Валерий	Юрьевич	79825232339	smirnovValera@gmai.com
\.


--
-- Data for Name: KataevProducts; Type: TABLE DATA; Schema: app; Owner: app
--

COPY app."KataevProducts" ("KataevId", "KataevName", "KataevArticle", "KataevType") FROM stdin;
1	Телефон Виво	0001	Техника
2	Планшет IPad Pro	0002	Техника
3	Кофемашина DeLonghi PrimaDonna SOUL ECAM	0003	Бытовая техника
\.


--
-- Data for Name: KataevSalesHistory; Type: TABLE DATA; Schema: app; Owner: app
--

COPY app."KataevSalesHistory" ("KataevId", "KataevPartnerId", "KataevProductId", "KataevQuantity", "KataevSaleDate") FROM stdin;
1	1	1	10	2026-03-31 00:00:00
2	1	2	100	2026-03-31 00:00:00
3	2	2	200000	2026-03-31 00:00:00
\.


--
-- Name: KataevPartners_KataevId_seq; Type: SEQUENCE SET; Schema: app; Owner: app
--

SELECT pg_catalog.setval('app."KataevPartners_KataevId_seq"', 2, true);


--
-- Name: KataevProducts_KataevId_seq; Type: SEQUENCE SET; Schema: app; Owner: app
--

SELECT pg_catalog.setval('app."KataevProducts_KataevId_seq"', 3, true);


--
-- Name: KataevSalesHistory_KataevId_seq; Type: SEQUENCE SET; Schema: app; Owner: app
--

SELECT pg_catalog.setval('app."KataevSalesHistory_KataevId_seq"', 3, true);


--
-- Name: KataevPartners PK_KataevPartners; Type: CONSTRAINT; Schema: app; Owner: app
--

ALTER TABLE ONLY app."KataevPartners"
    ADD CONSTRAINT "PK_KataevPartners" PRIMARY KEY ("KataevId");


--
-- Name: KataevProducts PK_KataevProducts; Type: CONSTRAINT; Schema: app; Owner: app
--

ALTER TABLE ONLY app."KataevProducts"
    ADD CONSTRAINT "PK_KataevProducts" PRIMARY KEY ("KataevId");


--
-- Name: KataevSalesHistory PK_KataevSalesHistory; Type: CONSTRAINT; Schema: app; Owner: app
--

ALTER TABLE ONLY app."KataevSalesHistory"
    ADD CONSTRAINT "PK_KataevSalesHistory" PRIMARY KEY ("KataevId");


--
-- Name: IX_KataevSalesHistory_KataevPartnerId; Type: INDEX; Schema: app; Owner: app
--

CREATE INDEX "IX_KataevSalesHistory_KataevPartnerId" ON app."KataevSalesHistory" USING btree ("KataevPartnerId");


--
-- Name: IX_KataevSalesHistory_KataevProductId; Type: INDEX; Schema: app; Owner: app
--

CREATE INDEX "IX_KataevSalesHistory_KataevProductId" ON app."KataevSalesHistory" USING btree ("KataevProductId");


--
-- Name: KataevSalesHistory FK_KataevSalesHistory_KataevPartners_KataevPartnerId; Type: FK CONSTRAINT; Schema: app; Owner: app
--

ALTER TABLE ONLY app."KataevSalesHistory"
    ADD CONSTRAINT "FK_KataevSalesHistory_KataevPartners_KataevPartnerId" FOREIGN KEY ("KataevPartnerId") REFERENCES app."KataevPartners"("KataevId") ON DELETE CASCADE;


--
-- Name: KataevSalesHistory FK_KataevSalesHistory_KataevProducts_KataevProductId; Type: FK CONSTRAINT; Schema: app; Owner: app
--

ALTER TABLE ONLY app."KataevSalesHistory"
    ADD CONSTRAINT "FK_KataevSalesHistory_KataevProducts_KataevProductId" FOREIGN KEY ("KataevProductId") REFERENCES app."KataevProducts"("KataevId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


